server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://c2s_project-loki-1:3100/loki/api/v1/push
   
scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: rails
    static_configs:
      - targets:
          - localhost
        labels:
          job: rails-logs
          __path__: /var/rails_log/*.log
